import java.util.ArrayList;

public class Challenge_2_EvenFibonacciNumbers
{
    /***
     *      Challenge: 2
     *      Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     *      By starting with 1 and 2, the first 10 terms will be:
     *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *      By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     *      find the sum of the even-valued terms.
     */

    public static void main(String[] args)
    {
        //Initialise sum of Even terms to 0
        int total = 0;
        //Set first 2 terms
        int lowerTerm = 1;
        int upperTerm = 2;
        //Add first upper term to sum as 2 is even
        total += upperTerm;
        //Whilst Upper term is not greater than four million
        while(upperTerm < 4000000)
        {
            //Determine next term
            int temp = lowerTerm + upperTerm;
            //Set lowerTerm to previous upperTerm
            //Set upperTerm to newly found term
            lowerTerm = upperTerm;
            upperTerm = temp;

            //Determine whether upperTerm is even
            if (upperTerm % 2 == 0)
            {
                //Add to total
                total += upperTerm;
            }
        }
        //Print total to console
        System.out.println("The sum of Even Fibonacci terms, not exceeding four million, is: " + total);
    }
}
